"""empty message

Revision ID: ae5675b78e42
Revises: f629823bf85e
Create Date: 2022-04-01 09:50:54.437269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5675b78e42'
down_revision = 'f629823bf85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'inventory')
    # ### end Alembic commands ###
